spring:
  config:
    import:
      - optional:configserver:http://ms-configserver:8888
  application:
    name: operation-service
  data:
    mongodb:
      database: db_operation
      host: localhost
      port: 27020
server:
  port: 8083
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-operation: /api/v1/operations
  path-operationType: /api/v1/operationTypes